In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv(r"C:\Users\sange\OneDrive\Attachments\Desktop\Attachments\Desktop\Job Market Analysis project\job market analysis project.csv")

In [4]:
df

,ID,Job_Title,Salary_Estimate,FIELD4,Rating,Company_Name,Location,Headquarters,Size,Founded,...,tensor,hadoop,tableau,bi,flink,mongo,google_an,job_title_sim,seniority_by_title,Degree
0,0,Data Scientist,$53K-$91K (Glassdoor est.),NaN,3.8,Tecolote Research\n3.8,"Albuquerque, NM","Goleta, CA",501 - 1000,1973,...,0,0,1,1,0,0,0,data scientist,na,M
1,1,Healthcare Data Scientist,$63K-$112K (Glassdoor est.),NaN,3.4,University of Maryland Medical System\n3.4,"Linthicum, MD","Baltimore, MD",10000+,1984,...,0,0,0,0,0,0,0,data scientist,na,M
2,2,Data Scientist,$80K-$90K (Glassdoor est.),NaN,4.8,KnowBe4\n4.8,"Clearwater, FL","Clearwater, FL",501 - 1000,2010,...,0,0,0,0,0,0,0,data scientist,na,M
3,3,Data Scientist,$56K-$97K (Glassdoor est.),NaN,3.8,PNNL\n3.8,"Richland, WA","Richland, WA",1001 - 5000,1965,...,0,0,0,0,0,0,0,data scientist,na,na
4,4,Data Scientist,$86K-$143K (Glassdoor est.),NaN,2.9,Affinity Solutions\n2.9,"New York, NY","New York, NY",51 - 200,1998,...,0,0,0,0,0,0,0,data scientist,na,na
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
737,950,"Sr Scientist, Immuno-Oncology - Oncology",$58K-$111K (Glassdoor est.),NaN,3.9,GSK\n3.9,"Cambridge, MA","Brentford, United Kingdom",10000+,1830,...,0,0,0,0,0,0,0,other scientist,sr,M
738,951,Senior Data Engineer,$72K-$133K (Glassdoor est.),NaN,4.4,Eventbrite\n4.4,"Nashville, TN","San Francisco, CA",1001 - 5000,2006,...,0,1,0,0,0,0,0,data engineer,sr,na
739,952,"Project Scientist - Auton Lab, Robotics Institute",$56K-$91K (Glassdoor est.),NaN,2.6,Software Engineering Institute\n2.6,"Pittsburgh, PA","Pittsburgh, PA",501 - 1000,1984,...,0,0,0,0,0,0,0,other scientist,na,P
740,953,Data Science Manager,$95K-$160K (Glassdoor est.),NaN,3.2,"Numeric, LLC\n3.2","Allentown, PA","Chadds Ford, PA",Jan-50,-1,...,0,0,0,0,0,0,0,data scientist,na,na
741,955,Research Scientist – Security and Privacy,$61K-$126K (Glassdoor est.),NaN,3.6,Riverside Research Institute\n3.6,"Beavercreek, OH","Arlington, VA",501 - 1000,1967,...,0,0,0,0,0,0,0,other scientist,na,M

In [5]:
df.shape

(742, 42)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 742 entries, 0 to 741
Data columns (total 42 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ID                  742 non-null    int64
 1   Job_Title           742 non-null    object
 2   Salary_Estimate     742 non-null    object
 3   FIELD4              0 non-null      float64
 4   Rating              742 non-null    float64
 5   Company_Name        742 non-null    object
 6   Location            742 non-null    object
 7   Headquarters        742 non-null    object
 8   Size                742 non-null    object
 9   Founded             742 non-null    int64
 10  Type_of_ownership   742 non-null    object
 11  Industry            742 non-null    object
 12  Sector              742 non-null    object
 13  Revenue             742 non-null    object
 14  Competitors         742 non-null    object
 15  Hourly              742 non-null    int64
 16  Employer_provided   742 non-null    int64
 17  Lower_Salary        742 non-null    int64
 18  Upper_Salary        742 non-null    int64
 19  Avg_SalaryK         742 non-null    float64
 20  company_txt         742 non-null    object
 21  Job_Location        742 non-null    object
 22  Age                 742 non-null    int64
 23  Python              742 non-null    int64
 24  spark               742 non-null    int64
 25  aws                 742 non-null    int64
 26  excel               742 non-null    int64
 27  sql_                742 non-null    int64
 28  sas                 742 non-null    int64
 29  keras               742 non-null    int64
 30  pytorch             742 non-null    int64
 31  scikit              742 non-null    int64
 32  tensor              742 non-null    int64
 33  hadoop              742 non-null    int64
 34  tableau             742 non-null    int64
 35  bi                  742 non-null    int64
 36  flink               742 non-null    int64
 37  mongo               742 non-null    int64
 38  google_an           742 non-null    int64
 39  job_title_sim       742 non-null    object
 40  seniority_by_title  742 non-null    object
 41  Degree              742 non-null    object
dtypes: float64(3), int64(23), object(16)
memory usage: 243.6+ KB

In [8]:
df.describe()

,ID,FIELD4,Rating,Founded,Hourly,Employer_provided,Lower_Salary,Upper_Salary,Avg_SalaryK,Age,...,keras,pytorch,scikit,tensor,hadoop,tableau,bi,flink,mongo,google_an
count,742.000000,0.0,742.000000,742.000000,742.000000,742.000000,742.000000,742.000000,742.000000,742.000000,...,742.000000,742.000000,742.000000,742.000000,742.000000,742.000000,742.000000,742.000000,742.000000,742.000000
mean,469.129380,NaN,3.618868,1837.154987,0.032345,0.022911,74.754717,128.214286,101.484501,47.524259,...,0.039084,0.052561,0.072776,0.097035,0.167116,0.199461,0.075472,0.013477,0.049865,0.018868
std,279.793117,NaN,0.801210,497.183763,0.177034,0.149721,30.945892,45.128650,37.482449,53.839080,...,0.193925,0.223305,0.259944,0.296205,0.373331,0.399865,0.264329,0.115384,0.217813,0.136150
min,0.000000,NaN,-1.000000,-1.000000,0.000000,0.000000,15.000000,16.000000,15.500000,-1.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,221.500000,NaN,3.300000,1939.000000,0.000000,0.000000,52.000000,96.000000,73.500000,12.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,472.500000,NaN,3.700000,1988.000000,0.000000,0.000000,69.500000,124.000000,97.500000,25.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,707.750000,NaN,4.000000,2007.000000,0.000000,0.000000,91.000000,155.000000,122.500000,60.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,955.000000,NaN,5.000000,2019.000000,1.000000,1.000000,202.000000,306.000000,254.000000,277.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [9]:
df.columns

Index(['ID', 'Job_Title', 'Salary_Estimate', 'FIELD4', 'Rating',
       'Company_Name', 'Location', 'Headquarters', 'Size', 'Founded',
       'Type_of_ownership', 'Industry', 'Sector', 'Revenue', 'Competitors',
       'Hourly', 'Employer_provided', 'Lower_Salary', 'Upper_Salary',
       'Avg_SalaryK', 'company_txt', 'Job_Location', 'Age', 'Python', 'spark',
       'aws', 'excel', 'sql_', 'sas', 'keras', 'pytorch', 'scikit', 'tensor',
       'hadoop', 'tableau', 'bi', 'flink', 'mongo', 'google_an',
       'job_title_sim', 'seniority_by_title', 'Degree'],
      dtype='object')

In [27]:
print(df.shape[1])

41

In [11]:
df.dtypes

ID                      int64
Job_Title              object
Salary_Estimate        object
FIELD4                float64
Rating                float64
Company_Name           object
Location               object
Headquarters           object
Size                   object
Founded                 int64
Type_of_ownership      object
Industry               object
Sector                 object
Revenue                object
Competitors            object
Hourly                  int64
Employer_provided       int64
Lower_Salary            int64
Upper_Salary            int64
Avg_SalaryK           float64
company_txt            object
Job_Location           object
Age                     int64
Python                  int64
spark                   int64
aws                     int64
excel                   int64
sql_                    int64
sas                     int64
keras                   int64
pytorch                 int64
scikit                  int64
tensor                  int64
hadoop                  int64
tableau                 int64
bi                      int64
flink                   int64
mongo                   int64
google_an               int64
job_title_sim          object
seniority_by_title     object
Degree                 object
dtype: object

In [13]:
df.duplicated().sum()

np.int64(0)

In [15]:
print(df.duplicated().sum())

0

In [17]:
df.isnull().sum()

ID                      0
Job_Title               0
Salary_Estimate         0
FIELD4                742
Rating                  0
Company_Name            0
Location                0
Headquarters            0
Size                    0
Founded                 0
Type_of_ownership       0
Industry                0
Sector                  0
Revenue                 0
Competitors             0
Hourly                  0
Employer_provided       0
Lower_Salary            0
Upper_Salary            0
Avg_SalaryK             0
company_txt             0
Job_Location            0
Age                     0
Python                  0
spark                   0
aws                     0
excel                   0
sql_                    0
sas                     0
keras                   0
pytorch                 0
scikit                  0
tensor                  0
hadoop                  0
tableau                 0
bi                      0
flink                   0
mongo                   0
google_an               0
job_title_sim           0
seniority_by_title      0
Degree                  0
dtype: int64

In [29]:
newdf = df.dropna(axis=1)
newdf

,ID,Job_Title,Salary_Estimate,Rating,Company_Name,Location,Headquarters,Size,Founded,Type_of_ownership,...,tensor,hadoop,tableau,bi,flink,mongo,google_an,job_title_sim,seniority_by_title,Degree
0,0,Data Scientist,$53K-$91K (Glassdoor est.),3.8,Tecolote Research\n3.8,"Albuquerque, NM","Goleta, CA",501 - 1000,1973,Company - Private,...,0,0,1,1,0,0,0,data scientist,na,M
1,1,Healthcare Data Scientist,$63K-$112K (Glassdoor est.),3.4,University of Maryland Medical System\n3.4,"Linthicum, MD","Baltimore, MD",10000+,1984,Other Organization,...,0,0,0,0,0,0,0,data scientist,na,M
2,2,Data Scientist,$80K-$90K (Glassdoor est.),4.8,KnowBe4\n4.8,"Clearwater, FL","Clearwater, FL",501 - 1000,2010,Company - Private,...,0,0,0,0,0,0,0,data scientist,na,M
3,3,Data Scientist,$56K-$97K (Glassdoor est.),3.8,PNNL\n3.8,"Richland, WA","Richland, WA",1001 - 5000,1965,Government,...,0,0,0,0,0,0,0,data scientist,na,na
4,4,Data Scientist,$86K-$143K (Glassdoor est.),2.9,Affinity Solutions\n2.9,"New York, NY","New York, NY",51 - 200,1998,Company - Private,...,0,0,0,0,0,0,0,data scientist,na,na
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
737,950,"Sr Scientist, Immuno-Oncology - Oncology",$58K-$111K (Glassdoor est.),3.9,GSK\n3.9,"Cambridge, MA","Brentford, United Kingdom",10000+,1830,Company - Public,...,0,0,0,0,0,0,0,other scientist,sr,M
738,951,Senior Data Engineer,$72K-$133K (Glassdoor est.),4.4,Eventbrite\n4.4,"Nashville, TN","San Francisco, CA",1001 - 5000,2006,Company - Public,...,0,1,0,0,0,0,0,data engineer,sr,na
739,952,"Project Scientist - Auton Lab, Robotics Institute",$56K-$91K (Glassdoor est.),2.6,Software Engineering Institute\n2.6,"Pittsburgh, PA","Pittsburgh, PA",501 - 1000,1984,College / University,...,0,0,0,0,0,0,0,other scientist,na,P
740,953,Data Science Manager,$95K-$160K (Glassdoor est.),3.2,"Numeric, LLC\n3.2","Allentown, PA","Chadds Ford, PA",Jan-50,-1,Company - Private,...,0,0,0,0,0,0,0,data scientist,na,na
741,955,Research Scientist – Security and Privacy,$61K-$126K (Glassdoor est.),3.6,Riverside Research Institute\n3.6,"Beavercreek, OH","Arlington, VA",501 - 1000,1967,Nonprofit Organization,...,0,0,0,0,0,0,0,other scientist,na,M

In [25]:
print(df.columns)

Index(['ID', 'Job_Title', 'Salary_Estimate', 'Rating', 'Company_Name',
       'Location', 'Headquarters', 'Size', 'Founded', 'Type_of_ownership',
       'Industry', 'Sector', 'Revenue', 'Competitors', 'Hourly',
       'Employer_provided', 'Lower_Salary', 'Upper_Salary', 'Avg_SalaryK',
       'company_txt', 'Job_Location', 'Age', 'Python', 'spark', 'aws', 'excel',
       'sql_', 'sas', 'keras', 'pytorch', 'scikit', 'tensor', 'hadoop',
       'tableau', 'bi', 'flink', 'mongo', 'google_an', 'job_title_sim',
       'seniority_by_title', 'Degree'],
      dtype='object')

In [31]:
print(newdf.shape[1])

41

In [41]:
df['Company_Name'] = df['Company_Name'].str.split('\n').str[0]
df

,ID,Job_Title,Salary_Estimate,Rating,Company_Name,Location,Headquarters,Size,Founded,Type_of_ownership,...,Job_Location,Age,pytorch,scikit,tensor,hadoop,job_title_sim,seniority_by_title,Degree,skills
0,0,Data Scientist,$53K-$91K (Glassdoor est.),3.8,Tecolote Research,"Albuquerque, NM","Goleta, CA",501 - 1000,1973,Company - Private,...,NM,48,0,0,0,0,data scientist,na,M,"excel, sas, Python, tableau, bi"
1,1,Healthcare Data Scientist,$63K-$112K (Glassdoor est.),3.4,University of Maryland Medical System,"Linthicum, MD","Baltimore, MD",10000+,1984,Other Organization,...,MD,37,0,0,0,0,data scientist,na,M,Python
2,2,Data Scientist,$80K-$90K (Glassdoor est.),4.8,KnowBe4,"Clearwater, FL","Clearwater, FL",501 - 1000,2010,Company - Private,...,FL,11,0,0,0,0,data scientist,na,M,"spark, excel, sql_, sas, Python"
3,3,Data Scientist,$56K-$97K (Glassdoor est.),3.8,PNNL,"Richland, WA","Richland, WA",1001 - 5000,1965,Government,...,WA,56,0,0,0,0,data scientist,na,na,Python
4,4,Data Scientist,$86K-$143K (Glassdoor est.),2.9,Affinity Solutions,"New York, NY","New York, NY",51 - 200,1998,Company - Private,...,NY,23,0,0,0,0,data scientist,na,na,"excel, sql_, sas, Python"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
737,950,"Sr Scientist, Immuno-Oncology - Oncology",$58K-$111K (Glassdoor est.),3.9,GSK,"Cambridge, MA","Brentford, United Kingdom",10000+,1830,Company - Public,...,MA,191,0,0,0,0,other scientist,sr,M,aws
738,951,Senior Data Engineer,$72K-$133K (Glassdoor est.),4.4,Eventbrite,"Nashville, TN","San Francisco, CA",1001 - 5000,2006,Company - Public,...,TN,15,0,0,0,1,data engineer,sr,na,"spark, aws, sql_, Python"
739,952,"Project Scientist - Auton Lab, Robotics Institute",$56K-$91K (Glassdoor est.),2.6,Software Engineering Institute,"Pittsburgh, PA","Pittsburgh, PA",501 - 1000,1984,College / University,...,PA,37,0,0,0,0,other scientist,na,P,excel
740,953,Data Science Manager,$95K-$160K (Glassdoor est.),3.2,"Numeric, LLC","Allentown, PA","Chadds Ford, PA",Jan-50,-1,Company - Private,...,PA,-1,0,0,0,0,data scientist,na,na,excel
741,955,Research Scientist – Security and Privacy,$61K-$126K (Glassdoor est.),3.6,Riverside Research Institute,"Beavercreek, OH","Arlington, VA",501 - 1000,1967,Nonprofit Organization,...,OH,54,0,0,0,0,other scientist,na,M,Python

In [43]:
df

,ID,Job_Title,Salary_Estimate,Rating,Company_Name,Location,Headquarters,Size,Founded,Type_of_ownership,...,Job_Location,Age,pytorch,scikit,tensor,hadoop,job_title_sim,seniority_by_title,Degree,skills
0,0,Data Scientist,$53K-$91K (Glassdoor est.),3.8,Tecolote Research,"Albuquerque, NM","Goleta, CA",501 - 1000,1973,Company - Private,...,NM,48,0,0,0,0,data scientist,na,M,"excel, sas, Python, tableau, bi"
1,1,Healthcare Data Scientist,$63K-$112K (Glassdoor est.),3.4,University of Maryland Medical System,"Linthicum, MD","Baltimore, MD",10000+,1984,Other Organization,...,MD,37,0,0,0,0,data scientist,na,M,Python
2,2,Data Scientist,$80K-$90K (Glassdoor est.),4.8,KnowBe4,"Clearwater, FL","Clearwater, FL",501 - 1000,2010,Company - Private,...,FL,11,0,0,0,0,data scientist,na,M,"spark, excel, sql_, sas, Python"
3,3,Data Scientist,$56K-$97K (Glassdoor est.),3.8,PNNL,"Richland, WA","Richland, WA",1001 - 5000,1965,Government,...,WA,56,0,0,0,0,data scientist,na,na,Python
4,4,Data Scientist,$86K-$143K (Glassdoor est.),2.9,Affinity Solutions,"New York, NY","New York, NY",51 - 200,1998,Company - Private,...,NY,23,0,0,0,0,data scientist,na,na,"excel, sql_, sas, Python"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
737,950,"Sr Scientist, Immuno-Oncology - Oncology",$58K-$111K (Glassdoor est.),3.9,GSK,"Cambridge, MA","Brentford, United Kingdom",10000+,1830,Company - Public,...,MA,191,0,0,0,0,other scientist,sr,M,aws
738,951,Senior Data Engineer,$72K-$133K (Glassdoor est.),4.4,Eventbrite,"Nashville, TN","San Francisco, CA",1001 - 5000,2006,Company - Public,...,TN,15,0,0,0,1,data engineer,sr,na,"spark, aws, sql_, Python"
739,952,"Project Scientist - Auton Lab, Robotics Institute",$56K-$91K (Glassdoor est.),2.6,Software Engineering Institute,"Pittsburgh, PA","Pittsburgh, PA",501 - 1000,1984,College / University,...,PA,37,0,0,0,0,other scientist,na,P,excel
740,953,Data Science Manager,$95K-$160K (Glassdoor est.),3.2,"Numeric, LLC","Allentown, PA","Chadds Ford, PA",Jan-50,-1,Company - Private,...,PA,-1,0,0,0,0,data scientist,na,na,excel
741,955,Research Scientist – Security and Privacy,$61K-$126K (Glassdoor est.),3.6,Riverside Research Institute,"Beavercreek, OH","Arlington, VA",501 - 1000,1967,Nonprofit Organization,...,OH,54,0,0,0,0,other scientist,na,M,Python

In [44]:
df.columns

Index(['ID', 'Job_Title', 'Salary_Estimate', 'Rating', 'Company_Name',
       'Location', 'Headquarters', 'Size', 'Founded', 'Type_of_ownership',
       'Industry', 'Sector', 'Revenue', 'Competitors', 'Hourly',
       'Employer_provided', 'Lower_Salary', 'Upper_Salary', 'Avg_SalaryK',
       'company_txt', 'Job_Location', 'Age', 'pytorch', 'scikit', 'tensor',
       'hadoop', 'job_title_sim', 'seniority_by_title', 'Degree', 'skills'],
      dtype='object')

In [35]:
df

,ID,Job_Title,Salary_Estimate,Rating,Company_Name,Location,Headquarters,Size,Founded,Type_of_ownership,...,hadoop,tableau,bi,flink,mongo,google_an,job_title_sim,seniority_by_title,Degree,skills
0,0,Data Scientist,$53K-$91K (Glassdoor est.),3.8,Tecolote Research\n3.8,"Albuquerque, NM","Goleta, CA",501 - 1000,1973,Company - Private,...,0,1,1,0,0,0,data scientist,na,M,"excel, sas, Python, tableau, bi"
1,1,Healthcare Data Scientist,$63K-$112K (Glassdoor est.),3.4,University of Maryland Medical System\n3.4,"Linthicum, MD","Baltimore, MD",10000+,1984,Other Organization,...,0,0,0,0,0,0,data scientist,na,M,Python
2,2,Data Scientist,$80K-$90K (Glassdoor est.),4.8,KnowBe4\n4.8,"Clearwater, FL","Clearwater, FL",501 - 1000,2010,Company - Private,...,0,0,0,0,0,0,data scientist,na,M,"spark, excel, sql_, sas, Python"
3,3,Data Scientist,$56K-$97K (Glassdoor est.),3.8,PNNL\n3.8,"Richland, WA","Richland, WA",1001 - 5000,1965,Government,...,0,0,0,0,0,0,data scientist,na,na,Python
4,4,Data Scientist,$86K-$143K (Glassdoor est.),2.9,Affinity Solutions\n2.9,"New York, NY","New York, NY",51 - 200,1998,Company - Private,...,0,0,0,0,0,0,data scientist,na,na,"excel, sql_, sas, Python"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
737,950,"Sr Scientist, Immuno-Oncology - Oncology",$58K-$111K (Glassdoor est.),3.9,GSK\n3.9,"Cambridge, MA","Brentford, United Kingdom",10000+,1830,Company - Public,...,0,0,0,0,0,0,other scientist,sr,M,aws
738,951,Senior Data Engineer,$72K-$133K (Glassdoor est.),4.4,Eventbrite\n4.4,"Nashville, TN","San Francisco, CA",1001 - 5000,2006,Company - Public,...,1,0,0,0,0,0,data engineer,sr,na,"spark, aws, sql_, Python"
739,952,"Project Scientist - Auton Lab, Robotics Institute",$56K-$91K (Glassdoor est.),2.6,Software Engineering Institute\n2.6,"Pittsburgh, PA","Pittsburgh, PA",501 - 1000,1984,College / University,...,0,0,0,0,0,0,other scientist,na,P,excel
740,953,Data Science Manager,$95K-$160K (Glassdoor est.),3.2,"Numeric, LLC\n3.2","Allentown, PA","Chadds Ford, PA",Jan-50,-1,Company - Private,...,0,0,0,0,0,0,data scientist,na,na,excel
741,955,Research Scientist – Security and Privacy,$61K-$126K (Glassdoor est.),3.6,Riverside Research Institute\n3.6,"Beavercreek, OH","Arlington, VA",501 - 1000,1967,Nonprofit Organization,...,0,0,0,0,0,0,other scientist,na,M,Python

In [46]:
df.columns

Index(['ID', 'Job_Title', 'Salary_Estimate', 'Rating', 'Company_Name',
       'Location', 'Headquarters', 'Size', 'Founded', 'Type_of_ownership',
       'Industry', 'Sector', 'Revenue', 'Competitors', 'Hourly',
       'Employer_provided', 'Lower_Salary', 'Upper_Salary', 'Avg_SalaryK',
       'company_txt', 'Job_Location', 'Age', 'job_title_sim',
       'seniority_by_title', 'Degree'],
      dtype='object')

In [46]:
df.shape

(742, 26)

In [14]:
df.isnull().sum()

ID                    0
Job_Title             0
Salary_Estimate       0
Rating                0
Company_Name          0
Location              0
Headquarters          0
Size                  0
Founded               0
Type_of_ownership     0
Industry              0
Sector                0
Revenue               0
Competitors           0
Hourly                0
Employer_provided     0
Lower_Salary          0
Upper_Salary          0
Avg_SalaryK           0
company_txt           0
Job_Location          0
Age                   0
Python                0
spark                 0
aws                   0
excel                 0
sql_                  0
sas                   0
keras                 0
pytorch               0
scikit                0
tensor                0
hadoop                0
tableau               0
bi                    0
flink                 0
mongo                 0
google_an             0
job_title_sim         0
seniority_by_title    0
Degree                0
dtype: int64

In [65]:
df.to_csv('cleaned_job_market.csv', index=False)
df

,ID,Job_Title,Salary_Estimate,Rating,Company_Name,Location,Headquarters,Size,Founded,Type_of_ownership,...,Job_Location,Age,pytorch,scikit,tensor,hadoop,job_title_sim,seniority_by_title,Degree,skills
0,0,Data Scientist,$53K-$91K (Glassdoor est.),3.8,Tecolote Research,"Albuquerque, NM","Goleta, CA",501 - 1000,1973,Company - Private,...,NM,48,0,0,0,0,data scientist,na,M,"excel, sas, Python, tableau, bi"
1,1,Healthcare Data Scientist,$63K-$112K (Glassdoor est.),3.4,University of Maryland Medical System,"Linthicum, MD","Baltimore, MD",10000+,1984,Other Organization,...,MD,37,0,0,0,0,data scientist,na,M,Python
2,2,Data Scientist,$80K-$90K (Glassdoor est.),4.8,KnowBe4,"Clearwater, FL","Clearwater, FL",501 - 1000,2010,Company - Private,...,FL,11,0,0,0,0,data scientist,na,M,"spark, excel, sql_, sas, Python"
3,3,Data Scientist,$56K-$97K (Glassdoor est.),3.8,PNNL,"Richland, WA","Richland, WA",1001 - 5000,1965,Government,...,WA,56,0,0,0,0,data scientist,na,na,Python
4,4,Data Scientist,$86K-$143K (Glassdoor est.),2.9,Affinity Solutions,"New York, NY","New York, NY",51 - 200,1998,Company - Private,...,NY,23,0,0,0,0,data scientist,na,na,"excel, sql_, sas, Python"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
737,950,"Sr Scientist, Immuno-Oncology - Oncology",$58K-$111K (Glassdoor est.),3.9,GSK,"Cambridge, MA","Brentford, United Kingdom",10000+,1830,Company - Public,...,MA,191,0,0,0,0,other scientist,sr,M,aws
738,951,Senior Data Engineer,$72K-$133K (Glassdoor est.),4.4,Eventbrite,"Nashville, TN","San Francisco, CA",1001 - 5000,2006,Company - Public,...,TN,15,0,0,0,1,data engineer,sr,na,"spark, aws, sql_, Python"
739,952,"Project Scientist - Auton Lab, Robotics Institute",$56K-$91K (Glassdoor est.),2.6,Software Engineering Institute,"Pittsburgh, PA","Pittsburgh, PA",501 - 1000,1984,College / University,...,PA,37,0,0,0,0,other scientist,na,P,excel
740,953,Data Science Manager,$95K-$160K (Glassdoor est.),3.2,"Numeric, LLC","Allentown, PA","Chadds Ford, PA",Jan-50,-1,Company - Private,...,PA,-1,0,0,0,0,data scientist,na,na,excel
741,955,Research Scientist – Security and Privacy,$61K-$126K (Glassdoor est.),3.6,Riverside Research Institute,"Beavercreek, OH","Arlington, VA",501 - 1000,1967,Nonprofit Organization,...,OH,54,0,0,0,0,other scientist,na,M,Python

In [5]:
df = pd.read_csv(r"C:\Users\sange\Downloads\job_market_analysis.csv")

In [6]:
df

,ID,Job_Title,Rating,Company_Name,Location,Headquarters,Size,Founded,Type_of_ownership,Industry,...,Revenue,Lower_Salary,Upper_Salary,Avg_SalaryK,job_title_sim,seniority_by_title,Degree,Skills,Average Salary,Age
0,1,Data Scientist,3.8,Tecolote Research,"Albuquerque, NM","Goleta, CA",501 - 1000,1973.0,Private,Aerospace & Defense,...,$50 to $100 million (USD),53,91,72.0,data scientist,Not Specified,Master's,Python,72.0,53.0
1,1,Data Scientist,3.8,Tecolote Research,"Albuquerque, NM","Goleta, CA",501 - 1000,1973.0,Private,Aerospace & Defense,...,$50 to $100 million (USD),53,91,72.0,data scientist,Not Specified,Master's,Excel,72.0,53.0
2,1,Data Scientist,3.8,Tecolote Research,"Albuquerque, NM","Goleta, CA",501 - 1000,1973.0,Private,Aerospace & Defense,...,$50 to $100 million (USD),53,91,72.0,data scientist,Not Specified,Master's,SAS,72.0,53.0
3,1,Data Scientist,3.8,Tecolote Research,"Albuquerque, NM","Goleta, CA",501 - 1000,1973.0,Private,Aerospace & Defense,...,$50 to $100 million (USD),53,91,72.0,data scientist,Not Specified,Master's,Tableau,72.0,53.0
4,1,Data Scientist,3.8,Tecolote Research,"Albuquerque, NM","Goleta, CA",501 - 1000,1973.0,Private,Aerospace & Defense,...,$50 to $100 million (USD),53,91,72.0,data scientist,Not Specified,Master's,Power BI,72.0,53.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2147,952,Senior Data Engineer,4.4,Eventbrite,"Nashville, TN","San Francisco, CA",1001 - 5000,2006.0,Public,Internet,...,$100 to $500 million (USD),72,133,102.5,data engineer,sr,Not specified,SQL,102.5,20.0
2148,952,Senior Data Engineer,4.4,Eventbrite,"Nashville, TN","San Francisco, CA",1001 - 5000,2006.0,Public,Internet,...,$100 to $500 million (USD),72,133,102.5,data engineer,sr,Not specified,Hadoop,102.5,20.0
2149,953,"Project Scientist - Auton Lab, Robotics Institute",2.6,Software Engineering Institute,"Pittsburgh, PA","Pittsburgh, PA",501 - 1000,1984.0,College / University,Colleges & Universities,...,Unknown / Non-Applicable,56,91,73.5,other scientist,Not Specified,PhD,Excel,73.5,42.0
2150,954,Data Science Manager,3.2,"Numeric, LLC","Allentown, PA","Chadds Ford, PA",1-50,NaN,Private,Staffing & Outsourcing,...,$5 to $10 million (USD),95,160,127.5,data scientist,Not Specified,Not specified,Excel,127.5,NaN
2151,956,Research Scientist – Security and Privacy,3.6,Riverside Research Institute,"Beavercreek, OH","Arlington, VA",501 - 1000,1967.0,Nonprofit Organization,Federal Agencies,...,$50 to $100 million (USD),61,126,93.5,other scientist,Not Specified,Master's,Python,93.5,59.0